### ISSUE TITLE
Failed installation on Windows

### ISSUE THREAD

**Issue by idefy** [vecmezoni/gulp-xslt#1]
This plugin does not install on windows. 
Apparently it uses node_xslt which tries to build c++ code locally. NodeJs does not support this for Windows.
If you cannot or do not plan on Windows compatibilty it would be nice to be mentionned.
Else, it would be great for this plugin to be compatible on windows.

**Comment by vecmezoni** [comment]
I'm in the middle of migrating to https://github.com/albanm/node-libxslt which supports Windows build. There is problem with node 0.11 and 0.12 that i'm trying to fix in node-libxslt.

**Comment by vecmezoni** [comment]
Looks like now you can build this module with proper Python and .NET Framework installation (see https://github.com/vecmezoni/gulp-xslt/blob/master/appveyor.yml)
