### ISSUE TITLE
Can not get external param

### ISSUE THREAD

**Issue by iooK** [vecmezoni/gulp-xslt#3]
Hi,

How can I get "someVariable" or "orAnotherVariable" in xsl file, like in usage help ?

I tried with $someVariable but I can not get it. Can you put a better example please ?

**Comment by vecmezoni** [comment]
Hi

Check out https://github.com/vecmezoni/gulp-xslt/compare/improve-readme?expand=1.
Is it clear now how to use variables?

**Comment by vecmezoni** [comment]
Ok, i assume that it's clearer now
