### ISSUE TITLE
Python requirement not listed on the NPM page

### ISSUE THREAD

**Issue by Ross-Angus** [vecmezoni/gulp-xslt#5]
I might be mistaken, but Python seems to be a requirement for gulp-xslt, at least according to the console errors. This does not seem to be listed on the NPM page:

https://www.npmjs.com/package/gulp-xslt

**Comment by vecmezoni** [comment]
Could you provide log with the errors?

I think that Python might be needed for building bindings in https://www.npmjs.com/package/libxslt. Than it's libxslt's issue, not gulp-xslt

**Comment by Ross-Angus** [comment]
I suspect you could be right. I installed gulp-saxon and it seems to have deleted the old log file, unfortunately.

Looking at my console, it seems to suggest the issue is with libxmljs-mt.
