### ISSUE TITLE
Node 10 compatibility issue in libxml-mt

### ISSUE THREAD

**Issue by bosson** [vecmezoni/gulp-xslt#8]
As noted here: https://github.com/gagern/libxmljs/issues/12
I too cant get past node 9 in : 
'''
    %> npm install gulp-xslt --save-dev

    > libxmljs-mt@0.18.0 install ./node_modules/libxmljs-mt
    > node-gyp rebuild

  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
../src/libxmljs.cc:69:17: error: no member named 'IsDead' in 'v8::V8'
    if (v8::V8::IsDead())
        ~~~~~~~~^
1 error generated.
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
'''

libxmljs-mt seems stale.

**Comment by vecmezoni** [comment]
Thanks for reporting. I would suggest to wait until libxml-mt and https://github.com/albanm/node-libxslt/blob/master/package.json#L32 is updated.
